name: CI Pipeline with deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: run tests
        run: npm test

      - name: Deploy to Render
        if: success()
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK}}
